#!/usr/bin/env python3
"""native/build.py: native/lrn.js, the behaviour of the Webflow-native /editorials page (5 Oct 2026).

The native page is the live page's finished HTML, built in Webflow (no hidden page, no injected HTML, no
flash). What it still needs is everything the bundle DOES: dice and editions, the Window programme, the
podcast player, YouTube, roll-call hovers, Archive search, ⌘K, Wire, calendar, radio, subject overlay ...
Rewriting that would fork it, so this file is generated from lrw_bundle.txt on every publish
(stamp_and_push.sh), and the native page always runs the same modules as live, with three native changes:

  1. the edition seed: with no #e= in the URL, the page's own baked edition (".ed-mini" No.) is the seed,
     so the first deal reproduces exactly what is already painted. A re-roll deals a new one as on live.
  2. the "live inside the site's own chrome" module does not move #lrw: the page already has it in place
     (moving it put the About text above the page).
  3. the Timeline moment of the day reads tl/daily/YYYY-MM.json (tl_daily.py): one moment a day for
     everyone from ALL the Timeline's moments, and "One of N moments" (Peter: "it's always fetter").

The data payload rides inside lrn.js (as live's loader would put it in <script id="lr-data">). The page
loads lrn.js after the load event, pinned to the pointer's commit, so none of it touches first paint.
Every patch is asserted: if the bundle changes under it, this build fails loudly instead of shipping a
page that half works.
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
b = json.load(open(os.path.join(REPO, 'lrw_bundle.txt'), encoding='utf-8'))
js, data, tmpl = b['js'], b['data'], b['html']

# Zones dealt FROM the DOM (Sets builds its deck from the cards on the page; Readers shuffles the cards in place)
# would re-deal differently on a page that is already dealt. lrn.js puts back what live's template starts from, so
# the first deal with the baked seed reproduces exactly what is painted.
i = tmpl.find('class="dz-grid'); assert i > 0, 'native build: no Sets grid in the template'
DZ = re.findall(r'<article class="dz">.*?</article>', tmpl[i:tmpl.find('</section>', i)], re.S)
assert DZ, 'native build: no Sets cards in the template'
i = tmpl.find('class="rd-grid'); assert i > 0, 'native build: no Readers grid in the template'
RD = re.findall(r'<article class="reader[^"]*"[^>]*>\s*<h3 class="rd-word">([^<]+)</h3>', tmpl[i:tmpl.find('</section>', i)])
assert len(RD) >= 2, 'native build: Readers words not found'


def patch(src, old, new, what):
    n = src.count(old)
    assert n == 1, 'native build: %s anchor found %d times (expected 1); the bundle changed under it' % (what, n)
    return src.replace(old, new)


js = patch(js, "var s = m ? +m[1] : (1 + Math.floor(Math.random() * 999999));",
           "var s = m ? +m[1] : (window.__LRN_SEED || (1 + Math.floor(Math.random() * 999999)));", 'edition seed')
js = patch(js, "var baked = [].map.call(grid.querySelectorAll('article.dz'), function(a){ return { html: a.outerHTML }; });",
           "var baked = window.__LRN_DZ ? window.__LRN_DZ.map(function(h){ return { html: h }; }) : [].map.call(grid.querySelectorAll('article.dz'), function(a){ return { html: a.outerHTML }; });",
           'Sets deck')
js = patch(js, "if (lrw && foot && foot.parentNode && foot.parentNode !== lrw) foot.parentNode.insertBefore(lrw, foot);",
           "if (!window.__LRN && lrw && foot && foot.parentNode && foot.parentNode !== lrw) foot.parentNode.insertBefore(lrw, foot);",
           'chrome mover')

PROLOGUE = r'''/* Le Random Editorials, native page behaviour. GENERATED by native/build.py from lrw_bundle.txt: do not edit. */
(function(){
  window.__LRN = 1;
  var d = document.createElement('script'); d.id = 'lr-data'; d.type = 'application/json';
  d.textContent = %s; document.body.appendChild(d);
  var ed = document.querySelector('#lrw .ed-mini'), m = ed && ed.textContent.match(/(\d{3,})/);
  window.__LRN_SEED = m ? +m[1] : 0;
  window.__LRN_DZ = %s;
  var g = document.querySelector('#readers .rd-grid'), order = %s;
  if (g) order.forEach(function(w){ [].forEach.call(g.querySelectorAll('article.reader'), function(a){
    var h = a.querySelector('.rd-word'); if (h && h.textContent.trim() === w) g.appendChild(a); }); });
})();
''' % (json.dumps(data, ensure_ascii=False), json.dumps(DZ, ensure_ascii=False), json.dumps(RD, ensure_ascii=False))

EPILOGUE = r'''
/* ---------- native: the Timeline moment of the day, from every moment (tl/daily, tl_daily.py) ---------- */
(function(){
  var y = document.getElementById('tl-year'), t = document.getElementById('tl-title'), b = document.getElementById('tl-body');
  if (!y || !t || !b) return;
  var now = new Date(), key = now.getFullYear() + '-' + ('0' + (now.getMonth() + 1)).slice(-2);
  fetch(LRWB + 'tl/daily/' + key + '.json').then(function(r){ if (!r.ok) throw new Error(r.status); return r.json(); }).then(function(j){
    var e = j.d && j.d[String(now.getDate())]; if (!e) return;
    y.textContent = e.y; t.textContent = e.t; b.textContent = e.b;
    var a = y.closest('a'); if (a && e.s) a.href = 'https://timeline.lerandom.art/m/' + e.s;
    var meta = document.querySelector('.tl-wrap .tl-meta');
    if (meta && j.n) meta.textContent = 'One of ' + Number(j.n).toLocaleString('en-US') + ' moments across ten chapters, from 70,000 years ago to now, edited by Peter Bauman.';
  }).catch(function(){});
})();
'''

out = PROLOGUE + js + EPILOGUE
p = os.path.join(HERE, 'lrn.js')
open(p, 'w', encoding='utf-8').write(out)
print('native/lrn.js %d KB' % (len(out.encode('utf-8')) // 1024))
